### ISSUE TITLE
don't pollute window props

### ISSUE THREAD

**Issue by roberthodgen** [autodatadirect/async-ops#2]
We probably shouldn't pollute window's props. Also... what about having multiple async-ops instances on a single page?

https://github.com/autodatadirect/async-ops/blob/89053fd562af5bdfaf3198dcc20b21f36fde7259/src/index.js#L8

**Comment by frodare** [comment]
I agree this is not the best solution.  It is used enable mock mode.  We should at least check to see if the global is already created and if not avoid overwriting it.
