### ISSUE TITLE
Add Descriptive Error to Register when Required Name Parameter Not Correct

### ISSUE THREAD

**Issue by mrprim** [autodatadirect/async-ops#4]
The parameters for the registerOperation method are name, service, and mock.

When registering a service without a name the library should throw a descriptive error - e.g. -> Error("Unable to register: No service name has been provided").

When registering a service with a duplicate name, there should be a warning (but not a blocking error) saying that this is a duplicate service.

**Comment by Alemkin** [comment]
I'll also add an error for a missing operation
